[8.0.1.0.0][measurement_import_export_common]
open-synergy/opnsynid-measurement pull request #7
Opened 2019-09-03 17:10 UTC by mikevhe18

2019-09-03 22:38 UTC, andhit-r requested changes

2019-09-03 22:38 UTC, andhit-r commented on measurement_import_export_common/wizards/measurement_export.py
> +    _name = "measurement.export"
_description

2019-09-03 22:38 UTC, andhit-r commented on measurement_import_export_common/wizards/measurement_export.py
> +            u"kode_item",
Pakai bahasa inggris. Item Code.

2019-09-03 22:38 UTC, andhit-r commented on measurement_import_export_common/wizards/measurement_export.py
> +            u"name",
Nama measurement objectnya mana mike

2019-09-03 22:38 UTC, andhit-r commented on measurement_import_export_common/wizards/measurement_import.py
> +            "views": [(False, "form")],
Kenapa tidak pakai view_id saja? View yg digunakan kan cuma form.

2019-09-03 22:38 UTC, andhit-r commented on measurement_import_export_common/wizards/measurement_import.py
> +    _name = "measurement.import"
_description

2019-09-04 01:11 UTC, mikevhe18 commented on measurement_import_export_common/wizards/measurement_import.py
> +            "views": [(False, "form")],
Khan ini common mas, nanti ketika dipakai di object yang inherit kesini, view_idnya akan beda-beda

2019-09-04 04:28 UTC, merged